name: lint-format
on: [push, pull_request]

jobs:
  formatting:
    name: Black formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install Black
      run: pip install black[jupyter]==23.3
    - name: Run Black
      run: black --config=black.toml --check .

  linting:
    name: Flake8 linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install linters
      run: pip install flake8==6.0.0 flake8-docstrings==1.7.0
    - name: Run Flake8
      run: flake8
